server:
  port: 8081
spring:
  application:
    name: service01
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.233:8848
    sentinel:
      transport:
        dashboard: 192.168.1.233:8089


