server:
  port: 8081
spring:
  application:
    name: service01
  cloud:
    nacos:
      discovery:
        server-addr: wangtt.top:8848
    sentinel:
      transport:
        dashboard: wangtt.top:8089


