server:
  port: 8082
spring:
  application:
    name: service02
  cloud:
    nacos:
      discovery:
        server-addr: wangtt.top:8848
    sentinel:
      transport:
        dashboard: wangtt.top:8089