# 带 * 的是经常被修改的属性

# 需要生成的表名称  *
tableNameList:
  - t_agent_ledger_record

# 生成文件的绝对路径 *
generatePath: D:\hhh

# 生成java的共用包名(列: ctrl包的上一级) *
packageName: com.kz.pay.demo

# 项目名称(列: kzPlatformBI) *
projectName: kzPlatformPay

# 作者 *
author: huanghz

# 数据库配置 *
mysql:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://114.116.80.254:7002/pay_ls?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: kz_admin
  password: kz_admin123

# sql类型与java类型替换规则
replacementRule:
  VARCHAR: String
  BIGINT: Long
  INT: Integer
  DATE: java.util.Date
  DATETIME: java.util.Date
  DOUBLE: Double
  TEXT: String
  VARCHAR2: String
  NVARCHAR2: String
  NUMBER: Long
  CHAR: String
# 需要忽略的字段
ignoreColumn:
  - _ddm_lock
  - _slot

# 表名的前缀
tableRemovePrefixes: t_
# 是否生成ctrl文件(暂时无效)
generateCtrlAble: true
# 是否生成 dao文件(暂时无效)
generateDaoAble: true
# 是否生成entity文件(暂时无效)
generateEntityAble: true
# 是否生成service文件(暂时无效)
generateServiceAble: true