spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.197.146:8848
      config:
        server-addr: 192.168.197.146:8848
    sentinel:
      transport:
        dashboard: 192.168.197.146:8888
feign:
  sentinel:
    enabled: true
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"