// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package hhz.demo10.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hhz.demo10.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
