// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package hhz.demo10.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hhz.demo10.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hhz.demo10.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<hhz.demo10.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .hhz.demo10.proto.StudentResponse studentResponse = 1;</code>
   */
  hhz.demo10.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .hhz.demo10.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .hhz.demo10.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends hhz.demo10.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .hhz.demo10.proto.StudentResponse studentResponse = 1;</code>
   */
  hhz.demo10.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
